//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace TestRun_History.Models
{
    public partial class Clause
    {
        public int ID { get; set; }
        public int Index { get; set; }
        public string FieldName { get; set; }
        public string FieldType { get; set; }
        public string Operand { get; set; }
        public string Operator { get; set; }
        public string Value { get; set; }
        public int QueryID { get; set; }
        public Nullable<int> Group { get; set; }
    }
    
}
