//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace TestRun_History.Models
{
    public partial class Query
    {
        public Query()
        {
            this.Clauses = new HashSet<Clause>();
            this.Query1 = new HashSet<Query>();
        }
    
        public int QueryID { get; set; }
        public Nullable<int> FolderID { get; set; }
        public string leaf { get; set; }
        public string Name { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual ICollection<Clause> Clauses { get; set; }
        public virtual ICollection<Query> Query1 { get; set; }
        public virtual Query Query2 { get; set; }
    }
    
}
