//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace TestRun_History.Models
{
    public partial class Step
    {
        public int ID { get; set; }
        public int TR_Num { get; set; }
        public string StepDetail { get; set; }
        public string ExpectedResult { get; set; }
        public string Checked { get; set; }
        public string Comments { get; set; }
        public int TestRun_DataID { get; set; }
    }
    
}
