//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace TestRun_History.Models
{
    public partial class TestRun_HistoryEntities : DbContext
    {
        public TestRun_HistoryEntities()
            : base("name=TestRun_HistoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Clause> Clauses { get; set; }
        public DbSet<Query> Queries { get; set; }
        public DbSet<Step> Steps { get; set; }
        public DbSet<TestRun_Data> TestRun_Data { get; set; }
    }
}
