//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace TestRun_History.Models
{
    public partial class TestRun_Data
    {
        public int TR_Num { get; set; }
        public Nullable<int> TC_Num { get; set; }
        public string T_Summary { get; set; }
        public string T_Type { get; set; }
        public string T_Main_Component { get; set; }
        public string T_Feature_ID { get; set; }
        public string env_IDEA_Encoding { get; set; }
        public string env_OS { get; set; }
        public string env_User_Type { get; set; }
        public string T_Status { get; set; }
        public string TR_Created_By { get; set; }
        public Nullable<System.DateTime> TR_Date_Created { get; set; }
        public string TR_Last_Mod_By { get; set; }
        public Nullable<System.DateTime> TR_Date_Last_Mod { get; set; }
        public string product { get; set; }
        public string isAutomated { get; set; }
        public Nullable<int> Estimated_Time { get; set; }
        public string T_Variants { get; set; }
        public string ProblemStatement { get; set; }
        public string Build { get; set; }
        public string PartialFailNotes { get; set; }
        public string Folders { get; set; }
        public string Language { get; set; }
        public string Flavour { get; set; }
        public string Task { get; set; }
        public int TestRun_DataID { get; set; }
    }
    
}
